name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: shivadityas
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

      - name: Build and tag Docker image
        run: |
          docker build -t your_dockerhub_username/your_image_name:latest .
          docker tag your_dockerhub_username/your_image_name:latest your_dockerhub_username/your_image_name:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push your_dockerhub_username/your_image_name:latest
          docker push your_dockerhub_username/your_image_name:${{ github.sha }}
